spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:modgo
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create #create #none #update #validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        one-indexed-parameters: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
# Request method 'DELETE' not supported
  mvc:
    hiddenmethod:
      filter:
        enabled: true